### ISSUE TITLE
[FEATURE]- New conditional objects

### ISSUE THREAD

**Issue by KoduIsGreat** [KoduIsGreat/orca#6]
**Is your feature request related to a problem? Please describe.**
The current use of conditionals as just top level elements adds alot of visual confusion to the workflow document. as per our discussions @odav  i suggest we implement what we discussed

**description**
```yaml
if:  value > 5 # some conditional
do:
   - task: <truetask>
   - ...

- task: <next>
```
----------------------
```yaml
for: i, range(0,10) #  <var> , <expression>
do:
   - task: 0<i<10 task
   - ...
```
-----------------------
```yaml
switch: <cond> #condition must match a case or resolve to default
<case1>: 
         - task1
         -
<case2>
         - task2
         -

default: 
         - task3
         - 
```
-----------------------
```yaml
fork:
   - - task11
     - ...
   - - task21
     - ...
```
